---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-netbox-env
data:
  ALLOWED_HOSTS: '*'
  DB_HOST: postgres
  DB_NAME: netbox
  DB_PASSWORD: J5brHrAXFLQSif0K
  DB_USER: netbox
  EMAIL_FROM: netbox@bar.com
  EMAIL_PASSWORD: bar
  EMAIL_PORT: "25"
  EMAIL_SERVER: localhost
  EMAIL_TIMEOUT: "10"
  EMAIL_USERNAME: foo
  NETBOX_PASSWORD: guest
  NETBOX_USERNAME: guest
  SECRET_KEY: r8OwDznj!!dci
  SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
  SUPERUSER_EMAIL: admin@example.com
  SUPERUSER_NAME: admin
  SUPERUSER_PASSWORD: admin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-postgres-env
data:
  POSTGRES_DB: netbox
  POSTGRES_USER: netbox
  POSTGRES_PASSWORD: J5brHrAXFLQSif0K
  