apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-redis
  labels:
    app: netbox-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox-redis
  template:
    metadata:
      labels:
        app: netbox-redis
    spec:
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: netbox-redis-pv-claim
      containers:  
      - image: redis:5.0.3
        name: redis 
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /data
            name: redis
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: netbox-redis
  labels:
    app: netbox-redis
spec:
  clusterIP: None
  ports:
  - name: netbox-redis
    port: 6379
    targetPort: 6379
  selector:
    app: netbox-redis

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-redis-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbox-redis-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/netbox-redis-db"

