netbox:
  image: netboxcommunity/netbox:v2.9.8
  superuserName: admin
  superuserPassword: admin
  superuserEmail: admin@example.com

postgres:
  image: postgres:13.0-alpine
  password: J5brHrAXFLQSif0K
  dataPath: /data/k8s/netbox-postgres-db

redis:
  image: redis:6.0.9
  dataPath: /data/k8s/netbox-redis-db