netbox:
  image: netboxcommunity/netbox:v4.1.11
  superuserName: admin
  # please edit password
  superuserPassword: admin
  superuserEmail: admin@example.com
  # please edit secret key
  secretKey: qwertyuiopasdfghjklzxcvbnm
  basePath: 'netbox/'
  # change this to your host
  csrfOrigin: 'http://www.example.com'

nginx:
  image: nginx:1.27.4-alpine

postgres:
  image: postgres:13.19-alpine
  # please edit password
  password: J5brHrAXFLQSif0K
  persistentVolume:
    storageClass: "-"

redis:
  image: redis:6.2.6
  persistentVolume:
    storageClass: "-"
