netbox:
  image: netboxcommunity/netbox:v3.0.10
  superuserName: admin
  # please edit password
  superuserPassword: admin
  superuserEmail: admin@example.com
  # please edit secret key
  secretKey: qwertyuiopasdfghjklzxcvbnm
  basePath: 'netbox/'

nginx:
  image: nginx:1.19.8-alpine

postgres:
  image: postgres:13.5-alpine
  # please edit password
  password: J5brHrAXFLQSif0K
  persistentVolume:
    storageClass: "-"

redis:
  image: redis:6.2.6
  persistentVolume:
    storageClass: "-"