netbox:
  image: netboxcommunity/netbox:v2.10.6
  superuserName: admin
  # please edit password
  superuserPassword: admin
  superuserEmail: admin@example.com
  # please edit secret key
  secretKey: qwertyuiopasdfghjklzxcvbnm
  basePath: 'netbox/'

nginx:
  image: nginx:1.19.8-alpine

postgres:
  image: postgres:13.2-alpine
  # please edit password
  password: J5brHrAXFLQSif0K
  persistentVolume:
    storageClass: "-"

redis:
  image: redis:6.2.1
  persistentVolume:
    storageClass: "-"