---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-env
data:
  ALLOWED_HOSTS: '*'
  DB_HOST: {{ .Release.Name }}-postgres
  DB_NAME: netbox
  DB_USER: netbox
  DB_PASSWORD: {{ .Values.postgres.password }}
  EMAIL_FROM: netbox@bar.com
  EMAIL_PASSWORD: bar
  EMAIL_PORT: "25"
  EMAIL_SERVER: localhost
  EMAIL_TIMEOUT: "10"
  EMAIL_USERNAME: foo
  LOGIN_REQUIRED: "true"
  NETBOX_USERNAME: guest
  SECRET_KEY: {{ .Values.netbox.secretKey }}
  BASE_PATH: {{ .Values.netbox.basePath }}
  REDIS_HOST: {{ .Release.Name }}-redis
  REDIS_CACHE_HOST: {{ .Release.Name }}-redis
  REDIS_PORT: "6379"
  REDIS_CACHE_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_CACHE_DATABASE: "1"
  SUPERUSER_EMAIL: {{ .Values.netbox.superuserEmail }}
  SUPERUSER_NAME: {{ .Values.netbox.superuserName }}
  SUPERUSER_PASSWORD: {{ .Values.netbox.superuserPassword }}
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      tcp_nopush     on;
      keepalive_timeout  65;
      gzip  on;
      server_tokens off;
      server {
          listen 80;
          server_name _;
          access_log off;
          location /{{ .Values.netbox.basePath }}static/ {
            alias /opt/netbox/netbox/static/;
          }

          location / {
            proxy_pass http://127.0.0.1:8001;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-env
data:
  POSTGRES_DB: netbox
  POSTGRES_USER: netbox
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  