apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: netbox
        image: {{ .Values.netbox.image }}
        resources:
          limits:
            cpu: 1000m
            memory: 300Mi
        ports:
        - containerPort: 8001
        env:
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: ALLOWED_HOSTS
              name: {{ .Release.Name }}-app-env
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: {{ .Release.Name }}-app-env
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: {{ .Release.Name }}-app-env
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: {{ .Release.Name }}-app-env
        - name: EMAIL_FROM
          valueFrom:
            configMapKeyRef:
              key: EMAIL_FROM
              name: {{ .Release.Name }}-app-env
        - name: EMAIL_PORT
          valueFrom:
            configMapKeyRef:
              key: EMAIL_PORT
              name: {{ .Release.Name }}-app-env
        - name: EMAIL_SERVER
          valueFrom:
            configMapKeyRef:
              key: EMAIL_SERVER
              name: {{ .Release.Name }}-app-env
        - name: EMAIL_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: EMAIL_TIMEOUT
              name: {{ .Release.Name }}-app-env
        - name: EMAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              key: EMAIL_USERNAME
              name: {{ .Release.Name }}-app-env
        - name: NETBOX_USERNAME
          valueFrom:
            configMapKeyRef:
              key: NETBOX_USERNAME
              name: {{ .Release.Name }}-app-env
        - name: BASE_PATH
          valueFrom:
            configMapKeyRef:
              key: BASE_PATH
              name: {{ .Release.Name }}-app-env
        - name: LOGIN_REQUIRED
          valueFrom:
            configMapKeyRef:
              key: LOGIN_REQUIRED
              name: {{ .Release.Name }}-app-env
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: {{ .Release.Name }}-app-env
        - name: REDIS_CACHE_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_CACHE_HOST
              name: {{ .Release.Name }}-app-env
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: {{ .Release.Name }}-app-env
        - name: REDIS_CACHE_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_CACHE_PORT
              name: {{ .Release.Name }}-app-env
        volumeMounts:
        - name: netbox-db-password
          mountPath: /run/secrets/db_password
          subPath: DB_PASSWORD
          readOnly: true
        - name: netbox-email-password
          mountPath: /run/secrets/email_password
          subPath: EMAIL_PASSWORD
          readOnly: true
        - name: netbox-secret-key
          mountPath: /run/secrets/secret_key
          subPath: SECRET_KEY
          readOnly: true
        - name: netbox-superuser-password
          mountPath: /run/secrets/superuser_password
          subPath: SUPERUSER_PASSWORD
          readOnly: true
      
      # nginx container
      - name: nginx
        image: {{ .Values.nginx.image }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: netbox-nginx-config
            subPath: nginx.conf
            mountPath: /etc/nginx/nginx.conf

      restartPolicy: Always
      volumes:
      # passwords
      - name: netbox-db-password
        configMap:
          name: {{ .Release.Name }}-app-env
          items:
            - key: DB_PASSWORD
              path: DB_PASSWORD
      - name: netbox-email-password
        configMap:
          name: {{ .Release.Name }}-app-env
          items:
            - key: EMAIL_PASSWORD
              path: EMAIL_PASSWORD
      - name: netbox-secret-key
        configMap:
          name: {{ .Release.Name }}-app-env
          items:
            - key: SECRET_KEY
              path: SECRET_KEY
      - name: netbox-superuser-password
        configMap:
          name: {{ .Release.Name }}-app-env
          items:
            - key: SUPERUSER_PASSWORD
              path: SUPERUSER_PASSWORD
      # nginx
      - name: netbox-nginx-config
        configMap:
          name: {{ .Release.Name }}-app-env
          items:
            - key: nginx.conf
              path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: ClusterIP
  ports:
  - name: netbox
    port: 80
  selector:
    app: {{ .Release.Name }}-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}-ingress
spec:
  rules:
  - http:
      paths:
      - path: /netbox
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-app
            port:
              number: 80
