apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pv-claim
      containers:  
      - image: {{ .Values.postgres.image }}
        name: postgres 
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: {{ .Release.Name }}-postgres-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: {{ .Release.Name }}-postgres-env      
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ .Release.Name }}-postgres-env
          
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  clusterIP: None
  ports:
  - name: netbox-postgres
    port: 5432
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pv-claim
spec:
{{- if .Values.postgres.persistentVolume.storageClass }}
{{- if (eq "-" .Values.postgres.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.postgres.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
